apiVersion: apps/v1
kind: Deployment
metadata:
  name: csp-email
  namespace: cspapi
  labels:
    app: csp-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csp-email
  template:
    metadata:
      labels:
        app: csp-email
    spec:
      containers:
      - name: nateonbiz
        image: myregistry.mwportal.com:30001/cspapi/email:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      hostAliases:
      - ip: 211.188.180.36
        hostnames:
        - cspapi.sktelecom.com